services:
  api:
    image: atendai/evolution-api:v2.1.1 # verify the latest version at https://hub.docker.com/r/atendai/evolution-api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080
  
  postgres:
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    environment:
      - POSTGRES_PASSWORD=PASSWORD # change this password to production on the .env database configuration
    volumes:
      - evolution_postgres:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis:latest
    networks:
      - evolution-net
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    expose:
      - 6379

volumes:
  evolution_instances:
  evolution_redis:
  evolution_postgres:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
